export const POINTS = {
  POST_QUESTION: 5,
  POST_ANSWER: 10,
  ANSWER_ACCEPTED: 25,
  RECEIVE_UPVOTE: 2,
  RECEIVE_DOWNVOTE: -1,
  POST_COMMENT: 2,
  WRITE_REVIEW: 5,
  PUBLISH_ARTICLE: 15,
  ENDORSE_SKILL: 1,
  RECEIVE_ENDORSEMENT: 3,
} as const;
